### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by jlauinger** [d120/dashboard#1]
Are you really sure this should be done in Java? I would argue that contributions will be very much more unlikely, also deployment is quite difficult.

Wouldn't PHP, Python, or Javascript make for a better choice?

**Comment by fdamken** [comment]
I am much more experienced in developing Java Webapps in a short time (especially when using [Spring Boot]) and that is why I chose Java for the backend.

Deployment is, if you have Java 7 installed on the server, not so difficult because the project uses [Spring Boot] whose Maven plugin creates an executable file that can be deployed to a server without any modifications as you can set the application mode to `service` which will make the JAR file to act as a start/stop-daemon script for the embedded application. It also puts all dependencies into a single JAR file so it is really not required to download any external dependencies or to set up a web container (e.g. Tomcat)

Furthermore I know that the API used for querying the departures ([Public Transport Enabler]) works and it is indirectly used by many people (it is the API that is used within Öffi).

[Spring Boot]: https://projects.spring.io/spring-boot/
[Public Transport Enabler]: https://github.com/schildbach/public-transport-enabler

**Comment by jnhmn** [comment]
Please be aware, that web sockets might not to be usable in this setup, since it will most likely be deployed behind a reverse proxy.

**Comment by jlauinger** [comment]
Nah I think that's good.

```
jlauinger@turret ~ $ sudo apachectl -V
Server version: Apache/2.4.10 (Debian)
```

With Apache 2.4 websockets are pretty much a `ProxyPass /ws2 ws://127.0.0.1:9000` away.

https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

**Comment by fdamken** [comment]
I forgot about the Apache Proxy but Websockets are not used at the time I am writing this comment. They are just added as a dependency 😅

But it is nice to know that Apache supports proxying of Websockets 😊
